name: Go Library CI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "**/v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Pull new module version
        run: go mod tidy

      - name: Build the project
        run: go build ./...

      - name: Run tests
        run: go test ./...

      - name: Generate Documentation (Optional)
        run: |
          go install golang.org/x/tools/cmd/godoc@latest
          godoc -http=:6060 &

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Create GitHub Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
